#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "local"
hooks = [
  { id = "stylua", name = "stylua", language = "system", entry = "stylua --check", files = "\\.lua$", pass_filenames = true },
  { id = "selene", name = "selene", language = "system", entry = "selene", files = "\\.lua$", pass_filenames = true },
]
