local Image = require("sixel-graphics.image")

describe("Image.from_file", function()
  it("produces unique sequential IDs", function()
    local a = Image.from_file("/tmp/a.png")
    local b = Image.from_file("/tmp/b.png")
    local c = Image.from_file("/tmp/c.png")

    assert.are.equal("img-1", a.id)
    assert.are.equal("img-2", b.id)
    assert.are.equal("img-3", c.id)
  end)

  it("normalizes relative paths to absolute", function()
    local img = Image.from_file("test.png")
    local cwd = vim.fn.getcwd()
    assert.are.equal(cwd .. "/test.png", img.path)
  end)

  it("preserves already-absolute paths", function()
    local img = Image.from_file("/absolute/path.png")
    assert.are.equal("/absolute/path.png", img.path)
  end)

  it("defaults geometry fields to zero/nil when no opts given", function()
    local img = Image.from_file("/tmp/img.png")
    assert.are.equal(0, img.geometry.x)
    assert.are.equal(0, img.geometry.y)
    assert.is_nil(img.geometry.width)
    assert.is_nil(img.geometry.height)
  end)

  it("applies opts to geometry fields", function()
    local img = Image.from_file("/tmp/img.png", { x = 5, y = 10, width = 40, height = 20 })
    assert.are.equal(5, img.geometry.x)
    assert.are.equal(10, img.geometry.y)
    assert.are.equal(40, img.geometry.width)
    assert.are.equal(20, img.geometry.height)
  end)

  it("accepts partial opts", function()
    local img = Image.from_file("/tmp/img.png", { x = 3, height = 15 })
    assert.are.equal(3, img.geometry.x)
    assert.are.equal(0, img.geometry.y)
    assert.is_nil(img.geometry.width)
    assert.are.equal(15, img.geometry.height)
  end)

  it("sets is_rendered to false", function()
    local img = Image.from_file("/tmp/img.png")
    assert.is_false(img.is_rendered)
  end)
end)
